default: &default
  adapter: postgresql
  schema_search_path: "public, shared_extensions"
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  port: 5432
  username: <%= ENV.fetch('DB_USER', 'ninja') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'ninja') %>

development:
  <<: *default
  database: ninja_development

test:
  <<: *default
  database: ninja_test

production:
  <<: *default
  database: ninja_production
